- name: Install jsonpath-ng
  hosts: localhost
  tasks:
    - name: Install jsonpath-ng
      ansible.builtin.pip:
        name: jsonpath-ng
      environment:
          PATH: "/home/runner/.local/bin:{{ lookup('env', 'PATH') }}"
