- name: Execute Python script
  hosts: localhost
  tasks:
    - name: Run Python script
      script: "{{ role_path }}/files/python/add_paths_to_epg.py"
      register: output

    - debug: var=output.stdout_lines
