- name: Check PETRO POC Ansible Virtual Environment
  hosts: localhost
  tasks:
    - name: Activate Ansible Virtual Environment
      ansible.builtin.shell:
        cmd: ./petro-poc/bin/activate.csh
      become: yes

    - name: Display the contents of the virtual environment directory
      ansible.builtin.shell:
        cmd: ls petro-poc
      register: venv_contents
