- name: Discover Python Environment
  hosts: localhost
  gather_facts: yes

  tasks:
    - name: Display Python Version
      ansible.builtin.shell:
        cmd: python3 --version
      register: python_version_output

    - name: Display Python Path
      ansible.builtin.shell:
        cmd: which python3
      register: python_path_output

    - name: Display Python Site Packages Directory
      ansible.builtin.shell:
        cmd: python3 -c "import site; print(site.getsitepackages()[0])"
      register: python_site_packages_output

    - name: Display Python Executable Path
      ansible.builtin.shell:
        cmd: python3 -c "import sys; print(sys.executable)"
      register: python_executable_output

    - name: Display Python Environment Variables
      ansible.builtin.shell:
        cmd: env | grep ^PYTHON
      register: python_env_vars_output

    - name: Display Installed Python Packages
      ansible.builtin.shell:
        cmd: pip3 list
      register: installed_packages_output
