- name: Create PETRO POC Ansible Virtual Environment
  hosts: localhost
  tasks:
    - name: Create a new Python virtual environment
      ansible.builtin.command:
        cmd: python3 -m venv petro-poc
      args:
        creates: petro-poc/bin/activate

    - name: Upgrade pip3
      ansible.builtin.shell:
        cmd: python3 -m pip install --upgrade pip
      register: venv_contents

    - name: Install jsonpath-ng
      ansible.builtin.pip:
        name: jsonpath-ng
    
    - name: Display Installed Python Packages
      ansible.builtin.shell:
        cmd: pip3 list
      register: installed_packages_output

    - name: Read CSV file
      read_csv:
        path: python/input_files/add_paths_to_epg.csv
        delimiter: ','
      register: add_paths_to_epg_csv

    - name: Run Python script
      script: python/add_paths_to_epg.py --csv-file "{{ add_paths_to_epg_csv.path }}"
      register: output

    - debug: var=output.stdout_lines